spring:
  profiles:
    active: local
  application:
    name: alert-matcher
  kafka:
    bootstrap-servers: ${kafka.bootstrap-servers}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        acks: all
        retries: 5
    topic:
      stock-alert: ${kafka.topic.stock-alert}
      trigger-alert: ${kafka.topic.trigger-alert}
    streams:
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: latest
      session.timeout.ms: 10000
      heartbeat.interval.ms: 3000
      max.poll.interval.ms: 30000

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      password: ${redis.password}  # ‚Üê ADD THIS
      username: ${redis.username}
      ssl:
        enabled: ${redis.ssl}


alert:
    type-list:
      - ABOVE
      - BELOW


server:
  port: 8083